import { NextResponse } from "next/server";

export async function GET() {
  const events = [
    {
      id: "sample-event",
      title: "Summer Music Festival 2024",
      organizer: "Trck Entertainment",
      date: "Saturday, August 24, 2024",
      time: "4:00 PM - 11:00 PM WAT",
      location: "O2 Arena, Victoria Island, Lagos",
      price: "$150.00",
      category: "Music",
      description: "Join us for an unforgettable night of music, art, and food. Featuring top international and local artists across two stages.",
      image: "/carnival-hero-bg.jpg",
      ticketsAvailable: 450,
      tags: ["Music", "Festival", "Nightlife", "Lagos"],
    },
    {
      id: "evt-hiphop-200s",
      title: "200s Hip Hop Night",
      organizer: "Mansory Club",
      date: "Friday, August 31, 2024",
      time: "9:00 PM - 4:00 AM WAT",
      location: "Mansory, Ikoyi, Lagos",
      price: "$50.00",
      category: "Nightlife",
      description: "Throwback 200s Hip Hop night with DJ sets, cocktails, and VIP tables.",
      image: "/carnival-hero-bg.jpg",
      ticketsAvailable: 120,
      tags: ["Party", "Hip Hop", "Nightlife"],
    },
    {
      id: "evt-afrobeats-sundown",
      title: "Afrobeats Sundown Live",
      organizer: "Lagoon Fest",
      date: "Saturday, September 14, 2024",
      time: "5:00 PM - 12:00 AM WAT",
      location: "Tarkwa Bay, Lagos",
      price: "$75.00",
      category: "Music",
      description: "Sunset performances, beach vibes, and live DJ sets from Lagos' hottest artists.",
      image: "/carnival-hero-bg.jpg",
      ticketsAvailable: 300,
      tags: ["Afrobeats", "Beach", "Concert"],
    },
    {
      id: "evt-business-summit",
      title: "Founders & Creators Summit",
      organizer: "Trck Business",
      date: "Wednesday, September 18, 2024",
      time: "10:00 AM - 4:00 PM WAT",
      location: "Lagos Oriental Hotel, Lagos",
      price: "$40.00",
      category: "Business",
      description: "A one-day summit for founders, creators, and growth-minded teams.",
      image: "/carnival-hero-bg.jpg",
      ticketsAvailable: 180,
      tags: ["Business", "Networking", "Creators"],
    },
    {
      id: "evt-arts-night",
      title: "Art & Culture After Dark",
      organizer: "City Arts Collective",
      date: "Friday, September 20, 2024",
      time: "6:30 PM - 11:00 PM WAT",
      location: "Alliance Francaise, Lagos",
      price: "$25.00",
      category: "Arts",
      description: "An intimate night of exhibitions, live performances, and local art experiences.",
      image: "/carnival-hero-bg.jpg",
      ticketsAvailable: 90,
      tags: ["Arts", "Culture", "Exhibition"],
    },
    {
      id: "evt-comedy-club",
      title: "Friday Comedy Club",
      organizer: "Punchline House",
      date: "Friday, September 27, 2024",
      time: "8:00 PM - 11:30 PM WAT",
      location: "Freedom Park, Lagos",
      price: "$20.00",
      category: "Entertainment",
      description: "Stand-up sets from rising comics and familiar faces on Lagos' comedy circuit.",
      image: "/carnival-hero-bg.jpg",
      ticketsAvailable: 220,
      tags: ["Comedy", "Entertainment", "Live"],
    },
  ];

  return NextResponse.json({ events });
}
